project_id = "fuvwfwkipsfnvpjefemt"

[functions.create-test-accounts]
verify_jwt = true

[functions.atlaas-ai-chat]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = true

[functions.send-receipt-email]
verify_jwt = true
